### ISSUE TITLE
[lcvvideo] Add BackgroundSubtractor{}

### ISSUE THREAD

**Issue by dinusv** [livecv/livecv#48]
http://docs.opencv.org/2.4/modules/video/doc/motion_analysis_and_object_tracking.html#backgroundsubtractor

**Comment by tvdstaaij** [comment]
I'm currently working on background subtractors. On this particular issue I'd like to note that `cv::BackgroundSubtractor` is just an abstract base class rather than a usable implementation, so there would not be a QML entity for it.

**Comment by dinusv** [comment]
I was thinking the base class for the BackgroundSubtractor would be used on components that can work with any configurable background subtractor:

```
Item{
   property BackgroundSubtractor bsub: BackgroundSubtractorMog{}
}
```

it's very similar to how the  ```QFeatureDetector```, and ```QFastFeatureDetector``` work, the ```BackgroundSubtractor``` does the processing, and all the other inheriting components deal with configuration.
