### ISSUE TITLE
Prepare Mac OS package

### ISSUE THREAD

**Issue by bgruszka** [livecv/livecv#55]
Hi,

Are you going to release package for Mac OS X? :)

Regards

**Comment by dinusv** [comment]
Hello,

I would like to and it's on my list, unfortunately I'm currently not in the possession of one and there's also the time I'll need to look over deployment on Mac OS. I'm still balancing between adding functionality, ease of use and deployment. I'd be happy to find someone for the deployment part on Mac OS, so if you'd be interested let me know!
