### ISSUE TITLE
SurfFeatureDetector is not a type

### ISSUE THREAD

**Issue by rafis** [livecv/livecv#70]
LGPL incompatible with SIFT/SURF license, but you can add checkbox in settings that makes the agreement with a user that he/she will use SIFT/SURF only for non-commercial purpose. Please add:

      SurfFeatureDetector {

      }
      
      SurfDescriptorExtractor {

      }

**Comment by dinusv** [comment]
Good ideea with the agreement, in Open CV 3 I think they are part of Open Contrib module, so I will have to see when I can integrate that as well.
