### ISSUE TITLE
Linker error building in Qt Creator on Windows

### ISSUE THREAD

**Issue by FexQuestForTerritory** [livecv/livecv#71]
Build environment

Windows 7 x64
OpenCV version = 2.4.11
OPENCV_DIR = C:\opencv\opencv\build\x86\vc12
Qt Creator 4.1.0 Based on Qt 5.7.0 (MSVC 2013, 32 bit)
Build Kit: Desktop Qt 5.7.0 MinGW 32 Bit

Run qmake, works ok.
Building produces the following linker errors:

C:\Users\txmobile\Downloads\livecv-master\livecv-master\lib\src\qmat.cpp:124: error: undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
C:\Users\txmobile\Downloads\livecv-master\livecv-master\lib\src\qmat.cpp:124: error: undefined reference to `cv::Mat::copyTo(cv::_OutputArray const&) const'
C:\opencv\opencv\build\include\opencv2\core\mat.hpp:125: error: undefined reference to `cv::Mat::copySize(cv::Mat const&)'
C:\opencv\opencv\build\include\opencv2\core\mat.hpp:278: error: undefined reference to `cv::fastFree(void*)'
C:\opencv\opencv\build\include\opencv2\core\mat.hpp:367: error: undefined reference to `cv::Mat::deallocate()'

Do I need to actually compile OpenCV with MinGW also instead of using the OpenCV binaries?

Any help would be very much appreciated.

**Comment by dinusv** [comment]
Unfortunately you have to since the visual studio libraries are not compatible with the mingw ones
