### ISSUE TITLE
lcvcore plugin

### ISSUE THREAD

**Issue by ashimpd** [livecv/livecv#94]
I did Launcher Based Installation on ubuntu 16.04. When I try to create a new project and do 
import lcvcore 1.0
It gives error ":2 module lcvcore not install".
Also directory plugins/lcvcore doesn't contain any file.
Can you please let me know from where to install plugins

**Comment by dinusv** [comment]
Which release did you use? Have you tried with version 1.4.1? (https://github.com/livecv/livecv/releases/download/v1.4.1/livecv-1.4.1-gcc-64-standalone.tar.gz)

"plugins/lcvcore" should be in your livecv installation directory.

**Comment by ashimpd** [comment]
thanks. I was using version 1.4
