### ISSUE TITLE
Module not installed

### ISSUE THREAD

**Issue by hobbs** [livecv/livecv#95]
I'm attempting to use a sample from the samples folder (Brute Force Matcher) and I'm just getting "module X is not installed" for every import in the sample:

![screenshot_20180215_102547](https://user-images.githubusercontent.com/37571/36273813-9b140d44-123a-11e8-9212-aaf13e61799e.png)

Here is the code I'm trying to use:
https://github.com/livecv/livecv/blob/master/samples/features2d/simplefeaturebruteforcematcher.qml

Environment information:
 - Ubuntu Linux 16.04
 - Using Launcher 1.4.0

There is no documentation as far as I can tell about using these plugins

**Comment by dinusv** [comment]
There seems to be a problem with that particular release, I'll have to look into it (https://github.com/livecv/livecv/issues/94). Version 1.4.1 doesn't have that problem: (https://github.com/livecv/livecv/releases/download/v1.4.1/livecv-1.4.1-gcc-64-standalone.tar.gz)

**Comment by hobbs** [comment]
Thanks for the quick reply, I get a different error now:
![screenshot_20180215_105523](https://user-images.githubusercontent.com/37571/36275116-c6d1dde0-123e-11e8-96a7-e95200975be7.png)

I do see liblive.so at `./plugins/live/liblive.so`

**Comment by dinusv** [comment]
Check if there's a folder ```/opt/livecv/link``` and check if livecv has write permissions in that folder. You might have create that manually and give it write permissions, then restart the application. Within the ```link``` folder, livecv creates symlinks towards libraries outside it's search path, so you should see one towards ```liblive``` popup.
