### ISSUE TITLE
Linux Standalone Install link gives 404

### ISSUE THREAD

**Issue by Chovin** [livecv/livecv#96]
The install link from http://livecv.dinusv.com/download.html : 
https://github.com/livecv/livecv/releases/download/v1.4.1/livecv-1.4.1-gcc-64-standalone.tar.gz
gives a 404.

How would I go about getting standalone version?

**Comment by dinusv** [comment]
I'm not sure why the links went offline, I've had the release rebuilt, so it should work now.

**Comment by Chovin** [comment]
awesome! it looks to be good. Thank you! was having a hell of a time building it from source :P
